### PR TITLE
Fix race condition when table is started

### PR DESCRIPTION
**Pull request by fk0815**
onTick() segfaults when m_iMultiplier is not initilized.

Signed-off-by: Frank Kunz <mailinglists@kunz-im-inter.net>

### CODE REVIEW

**Review by rzr — COMMENTED** [review]
this would not hurt but isnt m_iMultiplier initilialized just before ?

I am wondering why it was commented a in 1st place (e112c5be)

I suppose it is related to:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=979337

Maybe running valgrind would help

**Comment by fk0815** [comment]
The segfault I have seen is sporadic. It can be reproduced with the same sequence as described in the issue report on debian. By running it with gdb I found that m_iMultiplier had some arbitrary value when the issue was reproduced. I'm not the c++ expert, m_iMultiplier should be initialized I guess, but with the change in my commit I could not reproduce the issue anymore. Maybe some race condition with the onTick() function.

**Comment by rzr** [comment]
maybe you can diff valgrind traces with and without patch applied it will give us some hints.
does this only apply with gnu table what about hurd one  (it uses clear() ) ?

**Comment by fk0815** [comment]
I have seen that problem only with the gnu table.

**Pull request merged**
